#+TITLE:       Everyman睡眠计划
#+AUTHOR:      Shane Xu
#+EMAIL:       xusheng0711@gmail.com
#+DATE:        2016-03-07 Mon
#+URI:         /blog/%y/%m/%d/everyman-sleep-schedule-plain
#+KEYWORDS:    life, sleep
#+TAGS:        life, sleep
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 人生苦短

今年的冬天好长好长。

在我目前为止的人生的二十多个春秋里，我从未如此地抱怨过，冬天为何还不离去。

从春节前几天开始我的睡眠就急剧下降。起初只是很难入睡，往往要到一两点钟才能睡着，而后就愈发严重，变成三四点钟，最后竟然到了整宿都不能入眠的境况，有时候即便能够勉强睡着，也是梦境不断。想着年少不更的那段日子，总是挖空心思想写些，怪诞的场景的小说的时候怪自己总是能够沾枕即眠，酣眠无梦，而觉得怅然无比。然而我此时的境况却是哭笑不得。也许哪天有时间真应该把这些梦境穿起来，写个不成器的小说，也未尝不可尽管没怎么睡好，但是精神尚可，白天也不会感觉特别困倦，饮食也没有什么障碍，但是心里总是很害怕，就好像自己身体的睡眠（疲劳）开关被人关掉了一样，真怕到了某个时刻我的身体就会支持不住。这段时间老想着村上春树的《眠》这篇小说。想着自己是不是也会如，小说中的主人公那样最后被奇怪的小人们带走。

实在忍无可忍的时候，我终于下定决心去看病。友人们都说去看中医吧，于是我抱着试试看的心里，找了个据说专治失眠的老中医看了下。老中医切了我左右手的脉象，看了舌苔，问了下病情，就开始开药，前后不到5分钟，这真能管用吗。

然而，第一天晚上喝药之后我就奇迹般的容易睡着了。虽然中间断断续续醒来两次，但是有如产生了“我能睡着”这样的信念一般，我似乎多开了失眠给我带来的焦虑，配合着扯淡的4-7-8呼吸法（真正的4-7-8呼吸法，是一个外国的瑜伽大师提出的，最后的呼气是用嘴呼出，并且要发出一定的声音，其主要目的是为了放松身心。根本就不能快速入眠，只是国内那些没操守的小编乱写的稿子。）竟然勉勉强强睡了五六个小时吧。我本来就睡得少，也就不介意了，我只求能在正确的时间睡着就万事大吉了。在服药的这一个星期里，我的失眠症状也慢慢好转了，中间醒来的次数也慢慢变成一次。一次性睡眠时间有时也会达到4个小时。其中也有一晚上直到凌晨4点才睡着的，我想着那晚估计是心事太多导致的。第二周我又去复诊了，这次老中医只是把原先治疗脾虚的药换了，转而专治失眠。其间有一天我没有吃药，然而那天我睡的格外香。

前天因故外出，想着带着药出门实在有些不便，就放弃吃药了。也是因为前一天即便吃药的情况，也有思虑过多，而出现睡不着的情况。然而，我貌似已经看开了这个情况。对于失眠的焦虑，也慢慢减轻了。同时我也开始注意增加运动来调整身体，我只能说是调整，锻炼这样的词，这里是谈不上的。3月5日早上5点醒过来，我便再没有睡意了。于是拿着，手机不知道搜什么关键字，看到了一个everyman睡眠计划的东西。所谓的everyman睡眠计划，就是将原先的8小时睡眠，改成一个3~4小时主睡眠时段的加3~4个市场为20分钟~30分钟的小睡眠时段的结构。这样一天只需要睡4到5个小时，对于失眠熬夜加班的人来说是一种增加工作时间的睡眠方式。我想也许这样的睡眠计划才是真正适合我的，而5点起床这样的事情，对我来说从来都不是问题。从小学开始我基本就是5点起床的，直到工作后两年，这个习惯才开始慢慢变化，我变得慵懒了。

于是我根据自己的睡眠情况，定了一个也许能够让我适应的睡眠计划。\\
|时段|计划|
|----|----|
|23:30 - 05:30 |主睡眠|
|10:00 - 10:30|小睡眠|
|15:00 - 15:30|小睡眠|
|20:00 - 21:30 |健身|
|22:00 - 23:30|休闲|

