#+TITLE:       Happy Pi Day!
#+AUTHOR:      Shane Xu
#+EMAIL:       xusheng0711@gmail.com
#+DATE:        2016-03-15 Tue
#+URI:         /blog/%y/%m/%d/happy-pi-day
#+KEYWORDS:    海子
#+TAGS:        life
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 海子故居游记

产生去看看海子故居的想法，就是在几天前。对于我这个从来没有独自出过江浙沪地区的人也不失为一次不大不小的挑战。

3月13日早上8点30坐上，从杭州到安庆的大巴，整整在车上颠簸了五个半小时。期间我一直在问自己是不是太过任性了。诚然，我对这个自杀的诗人有着不可言喻的感觉，但是我并没有达到，某些人那样的狂热的状态。我对海子的认知也只是停留在，“我只愿面朝大海，春暖花开”，“姐姐, 今夜我在德令哈, 夜色笼罩”，“大风从东吹到西，从北刮到南，无视黑夜和黎明/你所说的曙光究竟是什么意思”。我向来都只是一个伪文青，只是近日实在苦闷，萌生了出去外面走走的想法。其实，就连生活了七八年的杭州的景点我都没有一一踏过，我实在是一个非常宅的人。

到了安庆后，辗转几番，终于在下午4点的时候，入住了事先预定好的旅馆。高河汽车站，然而我在那个三角地带，转了好多圈都没搞明白那个车站到底在什么地方，然后联想到安庆南站，我瞬间就没有脾气了。连安庆南站都是一个不起眼的小门洞，何况这个高河汽车站呢，找不到实在是太正常不过的事情了。

晚上八点的时候，外面飘来大妈们的黄梅戏和广场舞的声音。而我则百无聊赖的在看《唐顿庄园》，这个神奇的旅馆的电视机顶盒里竟然有这部剧。约莫十点半的时候我已经睡着了。我的失眠症算是好了一半，现在能睡着，只是算来算去最多只能睡5个小时左右。中间又会醒来一次，然后就是折磨人的滴答滴答了。果不其然，凌晨两点的时候我就醒了，关了电视机，满脑子各种神奇的想法，无奈拿出手机刷B站。也许四点我又睡着了吧，总之早上六点半我又醒了，于是对自己苦笑一番，便起身洗漱了。

七点半时我已经出了旅馆，在路边小摊草草解决了早饭之后，就踏上了我的朝圣之路。只有三公里左右的路程。沿途都是再普通不过的农村风景。低矮的房屋，不规则的农田，零星的桃树。四十多分钟我就到达了我的目的地。没有如预想搬那么激动，甚至可以说有些失望。海子故居，只是一间旧旧的平房。如果不是门前的石碑，如果不是大门口的书写着“海子故居”四个字的匾额，我很可能就会错过。我怀着些许激动和失望，走进了海子故居。我想整个参观过程我仅仅只用了十五分钟吧，因为能看的东西实在不多。客厅的三面墙上，挂着或者是张贴着各种匾额、介绍、字画，我只是粗略的看了下，然后拍了照片。而后便是海子的书房，那里陈列着海子生前使用过的文具以及他的三大柜子的书。我在那三大柜子的书前徘徊了好久，《霍夫曼志异小说选》、《实验心理学史》、《元史》、《马雅可夫斯基选集》、《莎士比亚选集》、《邪玛台国》……

从海子故居出来，我便慢慢踱步到了他的坟前。岔道口上的路牌标着“查氏祠堂”，实际走到的时候仅仅是几座坟茔。海子的墓，无疑是其中最为突出的。在他的坟前，有人留下了糕点，有人留下了杜康，有人留下了他的诗集，有人留下了自己的只言片语。而我只是静静地，坐在那里。想哭却哭不出来。过了好一会儿，我逐渐收拾好了心情，迅速地离开了那里。

又是好几小时的颠簸，我终于回到的“堵城”——杭州。

终究海子之于我只是一个能够写出温暖诗句的陌生人，他的死对我来说也仅仅是一个符号。对于若干年前，年轻的我的一个简单的谜题——一个能够写出如此温暖诗句的人，为何会选择卧轨自杀。

“从明天起，做一个幸福的人。”

