#+TITLE:       The Shape of Voice
#+AUTHOR:      Shane Xu
#+EMAIL:       xusheng0711@gmail.com
#+DATE:        2017-09-19 Tue
#+URI:         /blog/%y/%m/%d/the-shape-of-voice
#+KEYWORDS:    <TODO: insert your keywords here>
#+TAGS:        life
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: <TODO: insert your description here>

看完《你的名字》的时候，我就一直想写一篇影评。然而，却发现感触并不是那么深。记得那段时间，突然就冒出了一堆星海诚的粉丝来。然而，我真想问问那些，所谓的粉丝，“乃们知道《秒速五厘米》的副标题吗？乃们知道《秒速五厘米》中男主用的编程语言是什么吗？”在我心里，《你的名字》就是一部纯粹的商业片。

也许是因为《你的名字》的关系，《声之形》也惨遭一些非宅圈人士的围观。比如下面的评论：

#+BEGIN_QUOTE
将原著压缩在两小时内，删减和转折都太硬，使得角色性格转变和行为动机摸不着头脑。校园霸凌逐渐变成抑郁症的自我救赎，这些个人更无法代表广义的群体，由此发展出的情感更是矫揉造作。很多角色都没存在下去的理由，况且人物画风毫无辨识度，只能通过发型和发色去辨识，好多人脸被X挡着也就可想而知了。
#+END_QUOTE

很厉害，开头说一句“将原著压缩在两小时内”，从侧面点出仿佛自己看过原著。然后不痛不痒地指出了，所有漫改轻改作品的通病“删减和转折都太硬”，这样的话语几乎是不会错的。然而这一句“很多角色都没存在下去的理由，况且人物画风毫无辨识度，只能通过发型和发色去辨识”，原形毕露，想必这位这几年就看过了，《你的名字》这部动画电影，于是之前的所谓原著的说辞，就不知从何谈起了。

也许我是为了寻找共鸣，才不知好歹地上豆瓣去看个影评。结果豆瓣上的分数，国内公映后，每况愈下。在此之前，我是绝对没有想到这片子会引起各方人士撕逼的。

#+BEGIN_QUOTE
自闭症少年与斯德哥尔摩综合症少女，并不存在的爱情。物化女性到极致。女主既要毫无缘由暗恋一个每天虐待自己的男生，还要被剥夺说话的权力，成为一个纯粹被赏玩、无法自我表达的存在。对于导演来说，没有自我，需要被男性拯救，还只会不停道歉的女性，也许就代表了“纯爱”吧。 
#+END_QUOTE

“一千个读者就有一千个哈姆雷特”据说还有后半句，“但哈姆雷特不会变成李尔王”。所以原本是“校园霸凌”和“救赎”和“理解”主题的故事，怎么就变成了“纯爱”。因为听障而性感中略带自卑的硝子，怎么就变成了“斯德哥尔摩症候群”了。日本人的情感本就十分细腻（我想说国人也是，请看一下《金粉世家》，读一读“巴金”，哪怕重温下朱自清的《背影》），硝子的不停道歉，有部分源于自己的自卑，乞求以道歉的方式，被他人接受。然而这却是植野不能接受的。也许上面的评者，一路走来强横惯了吧。又或者如大部分所谓的村上春树的粉丝，只读过《挪威的森林》和部分的《1Q84》吧。

#+BEGIN_QUOTE
不要因为影片搭《你的名字。》便车就去看，故事，视觉，配乐都差太多。内地上映版本故事都没讲清楚，对于整体剧情的理解会比较困难。前半段不管是校园霸凌，还是两人萌生感情的几场戏，都让人挺感动的，但是这不足以支撑起一部电影。
#+END_QUOTE

内地上映的版本只减掉了二十分钟。我实在是不明白何谓没有把故事讲清楚。既然都点出霸凌主题了，没有这二十分钟并没有对你理解故事造成什么障碍。其实不应该再此和《你的名字》做比较。然而顺着这个评论的话锋，我也只能主观的说我自己的感想。《你的名字》前期很期待，在电影院里看的时候，中期产生不耐烦的情绪。我甚至没有二刷的想法。《声之形》在国内上映前我已经看了DVD版了，然后上映后我还是去了影院二刷。视觉，京阿尼和壁纸狂魔完全是两个路子，不知道这位看了《轻音少女》剧场版之后会作何感想。配乐，抱歉《你的名字》的BGM包括ED我都没有深刻的印象，完全没有《秒速五厘米》中的感觉。然而，《声之形》却完全不一样。BGM在不同场景下的音效都有细微的差别，最后的ED《恋をしたのは》我整整循环了一下午。京阿尼不愧是做了《轻音少女》和《吹响吧！上低音号》的“音乐”公司。

十一的时候，趁着在高铁上的无聊时光，终于把《追逐繁星的孩子》看完了。我看这片子主要还是为了ED《Hello Goodbye & Hello》，这首熊木杏里的歌，这首我在好多年前听过的歌，我当时不知道这是《追逐繁星的孩子》的ED。我想知道为什么有人会说出：

#+BEGIN_QUOTE
还记得听一次听，是看追逐繁星的孩子的预告片，一下子的一句Hello Goodbye & Hello ，心灵有被击到。
#+END_QUOTE

是啊，我竟然在这么多年之后才看到这部作品。

在最后让我回答之前提出的问题。《秒速五厘米》的副标题是“a chain of stories about their distance”。《秒速五厘米》中男主用的编程语言是PHP，而在小说版中则是C++。《秒速五厘米》对我来说是一部非常私人性质的作品。我也曾如远野贵志一般，失恋辞去工作在雪中踟躇。

最后还是分享一个尕丶天堂的[[https://www.bilibili.com/video/av14247605/?from=search&seid=14578639186932309937][视频]]。
#+BEGIN_EXPORT html
<div class="container">
  <iframe src="https://www.bilibili.com/blackboard/player.html?aid=14247605&cid=23256487&as_wide=1" frameborder="0" allowfullscreen class="video"></iframe>
</div>
#+END_EXPORT
