#+TITLE:       永远的开始
#+AUTHOR:      Shane Xu
#+EMAIL:       xusheng0711@gmail.com
#+DATE:        2009-12-18
#+URI:         /blog/%y/%m/%d/yong-yuan-de-kai-shi
#+KEYWORDS:    路
#+TAGS:        小说
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 永远的开始

集子开始于《雪》。

然而《雪》却从未停过。正如我的世界里始终下着那样的雪，因为，比之下雨，雪更有韵味，至少对我来说是这样的。


我们可以开始，开始我们的旅程了没有？


我开始写《影子》时，我不知道自己能走多久，就好像我曾提到过的场景那样，在某个没有月亮的晚上，走在黑暗的长廊，指引我的只有前人烟头的星火，对于我来说是一次绝好的尝试，倘若连这点星火也未曾给我，我想我只能默默地坐在原地。

或者我只是想通过我的小说，向你诉说我的故事。


《雪》算不上完整的小说吧，我一直想让它成为某一篇更为宏伟的小说的一个片断，比如在小说中的那个我，从某个咖啡吧出来，于是天空开始飘起，轻轻的雪花，然后，开始回忆起多年前的那场雪。回忆总是让人难以忍受，无论好坏，因为它们终究已是定局。


彼侧的开始。

我二十五岁，如果能顺顺当当地活到一百岁的话，我的生活已经过了四分之一。就好像不知不觉地吃下了半个蛋糕里的半个蛋糕。

后来，秋天到了。叶子，铺了了一路，我则等待着自己命运的转捩点。我的记忆在某处中断，我能想到的仅仅是，无限的下落，这时上面传来“你还好吗？”的问话，我只能摊摊手说，我也不知道，我还没有落地呢。


此侧的开始。

许多年以后。

我回到了 G 城。

20 岁时，我离开的城市。

一个无可救药的城市，一个无可救药到即使一个西装笔挺的中年男子，在满是人流的大街上对着分贝仪嚎出杀猪般的喊声致使数字跳至九十九，也不会有人为之停留一秒的城市。

我来到公墓，那是一座矮小的山丘，从高到低是一排排的花岗岩墓碑，再网上是一大片平地，不满了低矮的墓碑。墓碑之间点缀着几簇灌木。树，很小，但是很鲜亮。我不得不承认，这里的阳光较城里其他地方的要灿烂得多。


合二为一的开始。

我反复哼唱的歌曲，Fly Me to the Moon。

我反复默念的诗句，“大风从东刮到西，从北刮到南，无视黑夜和黎明，你所说的曙光究竟是什么意思。”

我反复寻找的东西，“那么，我所说的出口究竟在什么地方。”


正文。

这是多少年前做过的一个梦了。

从笔记本里撕去的手稿，我已经不知道收拾到何处了。


某天我撕去了那几页纸，我觉得我再也无法给我的开始安上正文。我想或许我是在等待着，等待着某天，我可以继续走下去。
